services:
  backend:
    build:
      context: ./
    depends_on:
      - database
    ports:
      - "8080:8080"
    container_name: ppurisam_backend
    networks:
      - ppurisam_network
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TOKEN_SECRET_KEY=${TOKEN_SECRET_KEY}
      - ACCESSTOKEN_PLUSTHOUR=${ACCESSTOKEN_PLUSTHOUR}
      - REFRESHTOKEN_PLUSHOUR=${REFRESHTOKEN_PLUSHOUR}

  database:
    image: mysql:8.0
    container_name: ppurisam_db
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

    ports:
      - "3306:3306"
    volumes:
      - ./db/ppurisam_data:/var/lib/mysql
    networks:
      - ppurisam_network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch-node
      - cluster.name=search-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    ports:
      - "9200:9200" # http
      - "9300:9300" # tcp
    networks:
      - ppurisam_network


networks:
  ppurisam_network:
