services:
  backend:
    build:
      context: ./
    depends_on:
      - database
    ports:
      - "8080:8080"
    container_name: ppurisam_backend
    networks:
      - ppurisam_network

  database:
    image: mysql:8.0
    container_name: ppurisam_db
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./db/ppurisam_data:/var/lib/mysql
    networks:
      - ppurisam_network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  ppurisam_network:
