global:
  scrape_interval: 15s #메트릭 수집 인터벌
  evaluation_interval: 15s #메트릭 평가 인터벌

scrape_configs:
  - job_name: 'prometheus-data'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']

  # Nginx Exporter 메트릭 수집
  - job_name: 'nginx'
    static_configs:
      - targets: [ 'nginx_prometheus_exporter:9113' ] # Nginx Exporter 컨테이너와 포트